### ISSUE TITLE
Reduce "What to Learn Next?" Section to Lower "Overload" ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tdd#118]
At present there are **_five_ links** listed in the "What to Learn Next?" section:
https://github.com/dwyl/learn-tdd#what-to-learn-next
![image](https://user-images.githubusercontent.com/194400/47958109-3de40700-dfbc-11e8-9dee-3333e6be4686.png)

I feel that this can be _overwhelming_ to people ... https://en.wikipedia.org/wiki/The_Paradox_of_Choice
I feel that we should limit this to three or even two links to avoid "overloading" people with options.

If it were up to me, I would recommend people jump straight to the **Todo List App** example,
but I _know_ that some people will find it _daunting_ ... 
it's not a 20 minute read, it's more like a weekend worth of focused effort (_for a beginner_).
It took me a _month_ (1 pomodoro per day) to write it, so I'd _estimate_ a couple of days for a beginner to read it and try writing the code ... 
Which is _why_ I feel we should leave in "Learn Tape" and "Learn Elm Architecture" ... 
as these are "gentler" and more "bitesize". 

# _Thoughts_?

## Todo (_Provisional_)

+ [ ] Cut out the following links/bullet points:
  + [ ] "Learn Istanbul" ... this is _way_ beyond the needs of  "beginner".
  + [ ] "Learn Daydream and Nightmare" ... 
  > this will be superceded by https://github.com/dwyl/learn-cypress.io soon ...

**Comment by codeshifu** [comment]
Don't you think it would it be helpful (for intermediate/expert folks) if we add a _feeling more adventurous?_ link to the learning resources we wanna cut out?

**Comment by nelsonic** [comment]
@codeshifu good question! 

While we would like to cater to _all_ levels of skill/experience we really want to *optimise* for complete beginners.

Imagine you’ve just learned to Kick a football and now your coach says: “good kick! now here’s how we’re going to win the World Cup...!”

Some people are *excited* by ambitious goals/targets, but others are instantly overwhelmed and thus “turned off” by the thought of something “difficult”. 

This tutorial (Learn-TDD) is meant to be beginner-friendly. So including *advanced* links can *overwhelm* and  *discourage* them. 

I *love* big challenges, and I can tell that you do too! But we need to *nurture* the people who haven’t yet built up the (self) confidence to approach the bigger problems.

Our “bigger plan” is to have a complete list of all our tutorials in (roughly) the linear order that people should learn them. 
See: https://github.com/dwyl/the-book/issues/69

Our even more “*ambitious*” goal is to help people eliminate the barriers to learning and build the mechanism to let them *track* their progress!

How did *you* first learn to program computers? 🤔

**Comment by iteles** [comment]
I agree with you that the _’paradox of choice’_ is real problem and can easily cause overwhelm for a number of people. 

But, from both my personal experience and watching many people go through the process of learning how to code, it’s the _choice_ that’s the problem, not the amount of materials. With a bit more direction, people are happy to focus their brains on the learning. 

Based on this and on @codeshifu’s great suggestion, maybe we could trial:
A) A little into paragraph on people levelling up & challenging themselves
B) Swapping our the _choice_ for an ordered list of ‘here’s what we suggest next’, each with a sentence on why 
C) Noting people are free to jump around to their heart’s desire, it’s not a prescriptive order, just one we have found works
