### ISSUE TITLE
TDD Best Practices?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-tdd#122]
Yesterday we got the following email thanking us for the Learn TDD tutorial: (_anonymised for privacy_)

![learn-tdd-tutorial-thankyou](https://user-images.githubusercontent.com/194400/54425256-c6ae4480-470c-11e9-9395-6cb6c6b0d532.png)

We increasingly get "thank you" emails from random strangers and that's great.
(_we don't **need** people to thank us for our free tutorials, because the motivation is intrinsic,
but it's nice when people thank us because it reminds us that **open source** docs **helps everyone**!_)

The _reason_ I'm sharing this email is simple: it has a **_specific_ request** for a call/session to go through TDD Best Practices with their team. This sort of "remote consulting" is _exactly_ what we intend to do once [@home](https://github.com/dwyl/home) is up-and-running. We will even have a dedicated "studio" (_with sound insulation, ideal lighting and [chroma-key background](https://github.com/dwyl/video/issues/10) ..._). **`before`** that happens, we can get a head start on capturing a few TDD best practices. 

# Todo

+ [ ] Collect as many thoughts as we can on Testing, TDD, software reliability & maintainability.
  > The objective at this stage is _quantity_ not perfection. (_we will condense and order them later!_)
+ [ ] Collate the thoughts into a prioritised list.
+ [ ] Stitch thoughts together into a well-written post that _anyone_ can read in 30 mins (_or less_)
+ [ ] _Publish_! 
+ [ ] Bonus Level: Make it a PDF that people can download and read on their mobile while commuting.
